# Generated by Django 5.0.3 on 2024-03-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mpapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='spotify_id',
            field=models.CharField(default='default_spotify_id', max_length=255, unique=True),
        ),
    ]
