# Generated by Django 5.0.3 on 2024-03-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mpapp', '0002_playlist_spotify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='href',
            field=models.URLField(default='https://default.com'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='image_url',
            field=models.URLField(default='https://default.com'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='owner',
            field=models.CharField(default='Default Owner', max_length=255),
        ),
        migrations.AddField(
            model_name='playlist',
            name='total_tracks',
            field=models.IntegerField(default=0),
        ),
    ]
