# Generated by Django 5.0.3 on 2024-03-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mpapp', '0005_song_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
