# Generated by Django 5.0.3 on 2024-03-27 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mpapp', '0007_alter_playlist_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='playlist',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='song',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='song',
            name='status',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='href',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='owner',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='spotify_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='status',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='total_tracks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_url',
            field=models.URLField(unique=True),
        ),
    ]
