# Generated by Django 5.0.3 on 2024-03-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mpapp', '0008_alter_playlist_managers_alter_song_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
